### ISSUE TITLE
Load jobs/schedules from database into seperate coravel startup.

### ISSUE THREAD

**Issue by lzinga** [jamesmh/coravelpro#1]
I have the current setup and am wondering if there is any way to let many "servers" use the task/jobs from the database.

![image](https://user-images.githubusercontent.com/9082450/59000444-5ec54280-87bf-11e9-81c1-18d8452f39f5.png)

This way I have one management portal that configures the jobs, and each controller loads the jobs from the database instead of hosting the entire management portal themselves. They instead will all have the same information.

If it helps at all my "Controllers" are self hosted signalr servers that the clients connect to and each client returns information back to the controllers. Which I am needing to setup on a schedule. So the schedules aren't running on the management portal website at all but instead each controller.

Let me know if you need any more information.

**Comment by jamesmh** [comment]
Right now there's on way to support this scenario. Are you wanting to schedule tasks on the "Web management" side only, and then run them on the controllers? Or only looking to execute jobs on-the-fly?

**Comment by lzinga** [comment]
The first one. Schedule on web while controllers run them. Where the controllers could just have read permissions to the database or something along those lines.

**Comment by jamesmh** [comment]
Ok, cool. Right now that's not supported since Coravel Pro itself does both the scheduling and executing of the jobs. 

So really for this to work there would need to be some new features added, something like you said:

- (a) A way to turn scheduling off yet still visually schedule things.
- (b) A way to turn the UI off but still pick up the scheduled tasks (which, in a scenario like yours would still have issues since all your controllers would be running the same scheduled jobs - potentially at the same time!)

As a side note, a distributed scheduling feature is something I'd like to build for Coravel, which - all things considered - might work for you in this kind of scenario. You just wouldn't get the UI to schedule jobs.

On the other hand, if a paying customer asks for a feature like this in Coravel Pro then I might consider it 😂

One option, for now, would be:

1. In your management system, set an environment variable or static field that indicates "this" system is the management one.

2. In your jobs/invocables, check if that field is set. If it is, then don't run the logic inside that job.

3. In your controllers, you can set the authentication for the portal to always fail - see here 👉(https://www.docs.pro.coravel.net/AdvancedConfiguration/#authorizing-access)

**Comment by lzinga** [comment]
You made a good point of how the management portal would deal with various controllers running the same job. Each one would need to be identifiable in some way to ensure that all jobs on each controller ran successfully.

> Make the controllers set that static constant or env variable to a different value so that the job logic will run

Are you saying that this would resolve the issue above or just make the management portal and jobs on controllers work nicer together?

Over all though I am glad to hear that a distributed scheduling feature is something you would want to build. For now I will try to figure something out.

**Comment by jamesmh** [comment]
This would resolve most of your issues lol The only remaining one is that your controllers would run the same schedule. So when a job is due, all 3 controllers (for example) will execute that same job.
